version: 0.2

phases:
  build:
    commands:
      - GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -tags lambda.norpc -o build/bootstrap cmd/main.go
artifacts:
  files:
    - api/build/*
    - index.html
    - index.js
    - conf.js